/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AuthenticatedPatientRouteImport } from './routes/_authenticated/patient'
import { Route as AuthenticatedMeetingRouteImport } from './routes/_authenticated/meeting'
import { Route as AuthenticatedDoctorRouteImport } from './routes/_authenticated/doctor'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedPatientIndexRouteImport } from './routes/_authenticated/patient.index'
import { Route as AuthenticatedDoctorIndexRouteImport } from './routes/_authenticated/doctor.index'
import { Route as AuthenticatedPatientUrgentRouteImport } from './routes/_authenticated/patient.urgent'
import { Route as AuthenticatedPatientProfileRouteImport } from './routes/_authenticated/patient.profile'
import { Route as AuthenticatedPatientBookRouteImport } from './routes/_authenticated/patient.book'
import { Route as AuthenticatedPatientAppointmentsRouteImport } from './routes/_authenticated/patient.appointments'
import { Route as AuthenticatedDoctorScheduleRouteImport } from './routes/_authenticated/doctor.schedule'
import { Route as AuthenticatedDoctorProfileRouteImport } from './routes/_authenticated/doctor.profile'
import { Route as AuthenticatedDoctorBookingsRouteImport } from './routes/_authenticated/doctor.bookings'
import { Route as AuthenticatedPatientPaymentIdRouteImport } from './routes/_authenticated/patient.payment.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const AuthenticatedPatientRoute = AuthenticatedPatientRouteImport.update({
  id: '/patient',
  path: '/patient',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMeetingRoute = AuthenticatedMeetingRouteImport.update({
  id: '/meeting',
  path: '/meeting',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDoctorRoute = AuthenticatedDoctorRouteImport.update({
  id: '/doctor',
  path: '/doctor',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPatientIndexRoute =
  AuthenticatedPatientIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPatientRoute,
  } as any)
const AuthenticatedDoctorIndexRoute =
  AuthenticatedDoctorIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDoctorRoute,
  } as any)
const AuthenticatedPatientUrgentRoute =
  AuthenticatedPatientUrgentRouteImport.update({
    id: '/urgent',
    path: '/urgent',
    getParentRoute: () => AuthenticatedPatientRoute,
  } as any)
const AuthenticatedPatientProfileRoute =
  AuthenticatedPatientProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedPatientRoute,
  } as any)
const AuthenticatedPatientBookRoute =
  AuthenticatedPatientBookRouteImport.update({
    id: '/book',
    path: '/book',
    getParentRoute: () => AuthenticatedPatientRoute,
  } as any)
const AuthenticatedPatientAppointmentsRoute =
  AuthenticatedPatientAppointmentsRouteImport.update({
    id: '/appointments',
    path: '/appointments',
    getParentRoute: () => AuthenticatedPatientRoute,
  } as any)
const AuthenticatedDoctorScheduleRoute =
  AuthenticatedDoctorScheduleRouteImport.update({
    id: '/schedule',
    path: '/schedule',
    getParentRoute: () => AuthenticatedDoctorRoute,
  } as any)
const AuthenticatedDoctorProfileRoute =
  AuthenticatedDoctorProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedDoctorRoute,
  } as any)
const AuthenticatedDoctorBookingsRoute =
  AuthenticatedDoctorBookingsRouteImport.update({
    id: '/bookings',
    path: '/bookings',
    getParentRoute: () => AuthenticatedDoctorRoute,
  } as any)
const AuthenticatedPatientPaymentIdRoute =
  AuthenticatedPatientPaymentIdRouteImport.update({
    id: '/payment/$id',
    path: '/payment/$id',
    getParentRoute: () => AuthenticatedPatientRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/doctor': typeof AuthenticatedDoctorRouteWithChildren
  '/meeting': typeof AuthenticatedMeetingRoute
  '/patient': typeof AuthenticatedPatientRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/doctor/bookings': typeof AuthenticatedDoctorBookingsRoute
  '/doctor/profile': typeof AuthenticatedDoctorProfileRoute
  '/doctor/schedule': typeof AuthenticatedDoctorScheduleRoute
  '/patient/appointments': typeof AuthenticatedPatientAppointmentsRoute
  '/patient/book': typeof AuthenticatedPatientBookRoute
  '/patient/profile': typeof AuthenticatedPatientProfileRoute
  '/patient/urgent': typeof AuthenticatedPatientUrgentRoute
  '/doctor/': typeof AuthenticatedDoctorIndexRoute
  '/patient/': typeof AuthenticatedPatientIndexRoute
  '/patient/payment/$id': typeof AuthenticatedPatientPaymentIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/meeting': typeof AuthenticatedMeetingRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/doctor/bookings': typeof AuthenticatedDoctorBookingsRoute
  '/doctor/profile': typeof AuthenticatedDoctorProfileRoute
  '/doctor/schedule': typeof AuthenticatedDoctorScheduleRoute
  '/patient/appointments': typeof AuthenticatedPatientAppointmentsRoute
  '/patient/book': typeof AuthenticatedPatientBookRoute
  '/patient/profile': typeof AuthenticatedPatientProfileRoute
  '/patient/urgent': typeof AuthenticatedPatientUrgentRoute
  '/doctor': typeof AuthenticatedDoctorIndexRoute
  '/patient': typeof AuthenticatedPatientIndexRoute
  '/patient/payment/$id': typeof AuthenticatedPatientPaymentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/doctor': typeof AuthenticatedDoctorRouteWithChildren
  '/_authenticated/meeting': typeof AuthenticatedMeetingRoute
  '/_authenticated/patient': typeof AuthenticatedPatientRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/_authenticated/doctor/bookings': typeof AuthenticatedDoctorBookingsRoute
  '/_authenticated/doctor/profile': typeof AuthenticatedDoctorProfileRoute
  '/_authenticated/doctor/schedule': typeof AuthenticatedDoctorScheduleRoute
  '/_authenticated/patient/appointments': typeof AuthenticatedPatientAppointmentsRoute
  '/_authenticated/patient/book': typeof AuthenticatedPatientBookRoute
  '/_authenticated/patient/profile': typeof AuthenticatedPatientProfileRoute
  '/_authenticated/patient/urgent': typeof AuthenticatedPatientUrgentRoute
  '/_authenticated/doctor/': typeof AuthenticatedDoctorIndexRoute
  '/_authenticated/patient/': typeof AuthenticatedPatientIndexRoute
  '/_authenticated/patient/payment/$id': typeof AuthenticatedPatientPaymentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/doctor'
    | '/meeting'
    | '/patient'
    | '/auth/callback'
    | '/doctor/bookings'
    | '/doctor/profile'
    | '/doctor/schedule'
    | '/patient/appointments'
    | '/patient/book'
    | '/patient/profile'
    | '/patient/urgent'
    | '/doctor/'
    | '/patient/'
    | '/patient/payment/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/meeting'
    | '/auth/callback'
    | '/doctor/bookings'
    | '/doctor/profile'
    | '/doctor/schedule'
    | '/patient/appointments'
    | '/patient/book'
    | '/patient/profile'
    | '/patient/urgent'
    | '/doctor'
    | '/patient'
    | '/patient/payment/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/dashboard'
    | '/_authenticated/doctor'
    | '/_authenticated/meeting'
    | '/_authenticated/patient'
    | '/auth/callback'
    | '/_authenticated/doctor/bookings'
    | '/_authenticated/doctor/profile'
    | '/_authenticated/doctor/schedule'
    | '/_authenticated/patient/appointments'
    | '/_authenticated/patient/book'
    | '/_authenticated/patient/profile'
    | '/_authenticated/patient/urgent'
    | '/_authenticated/doctor/'
    | '/_authenticated/patient/'
    | '/_authenticated/patient/payment/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authenticated/patient': {
      id: '/_authenticated/patient'
      path: '/patient'
      fullPath: '/patient'
      preLoaderRoute: typeof AuthenticatedPatientRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/meeting': {
      id: '/_authenticated/meeting'
      path: '/meeting'
      fullPath: '/meeting'
      preLoaderRoute: typeof AuthenticatedMeetingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/doctor': {
      id: '/_authenticated/doctor'
      path: '/doctor'
      fullPath: '/doctor'
      preLoaderRoute: typeof AuthenticatedDoctorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/patient/': {
      id: '/_authenticated/patient/'
      path: '/'
      fullPath: '/patient/'
      preLoaderRoute: typeof AuthenticatedPatientIndexRouteImport
      parentRoute: typeof AuthenticatedPatientRoute
    }
    '/_authenticated/doctor/': {
      id: '/_authenticated/doctor/'
      path: '/'
      fullPath: '/doctor/'
      preLoaderRoute: typeof AuthenticatedDoctorIndexRouteImport
      parentRoute: typeof AuthenticatedDoctorRoute
    }
    '/_authenticated/patient/urgent': {
      id: '/_authenticated/patient/urgent'
      path: '/urgent'
      fullPath: '/patient/urgent'
      preLoaderRoute: typeof AuthenticatedPatientUrgentRouteImport
      parentRoute: typeof AuthenticatedPatientRoute
    }
    '/_authenticated/patient/profile': {
      id: '/_authenticated/patient/profile'
      path: '/profile'
      fullPath: '/patient/profile'
      preLoaderRoute: typeof AuthenticatedPatientProfileRouteImport
      parentRoute: typeof AuthenticatedPatientRoute
    }
    '/_authenticated/patient/book': {
      id: '/_authenticated/patient/book'
      path: '/book'
      fullPath: '/patient/book'
      preLoaderRoute: typeof AuthenticatedPatientBookRouteImport
      parentRoute: typeof AuthenticatedPatientRoute
    }
    '/_authenticated/patient/appointments': {
      id: '/_authenticated/patient/appointments'
      path: '/appointments'
      fullPath: '/patient/appointments'
      preLoaderRoute: typeof AuthenticatedPatientAppointmentsRouteImport
      parentRoute: typeof AuthenticatedPatientRoute
    }
    '/_authenticated/doctor/schedule': {
      id: '/_authenticated/doctor/schedule'
      path: '/schedule'
      fullPath: '/doctor/schedule'
      preLoaderRoute: typeof AuthenticatedDoctorScheduleRouteImport
      parentRoute: typeof AuthenticatedDoctorRoute
    }
    '/_authenticated/doctor/profile': {
      id: '/_authenticated/doctor/profile'
      path: '/profile'
      fullPath: '/doctor/profile'
      preLoaderRoute: typeof AuthenticatedDoctorProfileRouteImport
      parentRoute: typeof AuthenticatedDoctorRoute
    }
    '/_authenticated/doctor/bookings': {
      id: '/_authenticated/doctor/bookings'
      path: '/bookings'
      fullPath: '/doctor/bookings'
      preLoaderRoute: typeof AuthenticatedDoctorBookingsRouteImport
      parentRoute: typeof AuthenticatedDoctorRoute
    }
    '/_authenticated/patient/payment/$id': {
      id: '/_authenticated/patient/payment/$id'
      path: '/payment/$id'
      fullPath: '/patient/payment/$id'
      preLoaderRoute: typeof AuthenticatedPatientPaymentIdRouteImport
      parentRoute: typeof AuthenticatedPatientRoute
    }
  }
}

interface AuthenticatedDoctorRouteChildren {
  AuthenticatedDoctorBookingsRoute: typeof AuthenticatedDoctorBookingsRoute
  AuthenticatedDoctorProfileRoute: typeof AuthenticatedDoctorProfileRoute
  AuthenticatedDoctorScheduleRoute: typeof AuthenticatedDoctorScheduleRoute
  AuthenticatedDoctorIndexRoute: typeof AuthenticatedDoctorIndexRoute
}

const AuthenticatedDoctorRouteChildren: AuthenticatedDoctorRouteChildren = {
  AuthenticatedDoctorBookingsRoute: AuthenticatedDoctorBookingsRoute,
  AuthenticatedDoctorProfileRoute: AuthenticatedDoctorProfileRoute,
  AuthenticatedDoctorScheduleRoute: AuthenticatedDoctorScheduleRoute,
  AuthenticatedDoctorIndexRoute: AuthenticatedDoctorIndexRoute,
}

const AuthenticatedDoctorRouteWithChildren =
  AuthenticatedDoctorRoute._addFileChildren(AuthenticatedDoctorRouteChildren)

interface AuthenticatedPatientRouteChildren {
  AuthenticatedPatientAppointmentsRoute: typeof AuthenticatedPatientAppointmentsRoute
  AuthenticatedPatientBookRoute: typeof AuthenticatedPatientBookRoute
  AuthenticatedPatientProfileRoute: typeof AuthenticatedPatientProfileRoute
  AuthenticatedPatientUrgentRoute: typeof AuthenticatedPatientUrgentRoute
  AuthenticatedPatientIndexRoute: typeof AuthenticatedPatientIndexRoute
  AuthenticatedPatientPaymentIdRoute: typeof AuthenticatedPatientPaymentIdRoute
}

const AuthenticatedPatientRouteChildren: AuthenticatedPatientRouteChildren = {
  AuthenticatedPatientAppointmentsRoute: AuthenticatedPatientAppointmentsRoute,
  AuthenticatedPatientBookRoute: AuthenticatedPatientBookRoute,
  AuthenticatedPatientProfileRoute: AuthenticatedPatientProfileRoute,
  AuthenticatedPatientUrgentRoute: AuthenticatedPatientUrgentRoute,
  AuthenticatedPatientIndexRoute: AuthenticatedPatientIndexRoute,
  AuthenticatedPatientPaymentIdRoute: AuthenticatedPatientPaymentIdRoute,
}

const AuthenticatedPatientRouteWithChildren =
  AuthenticatedPatientRoute._addFileChildren(AuthenticatedPatientRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDoctorRoute: typeof AuthenticatedDoctorRouteWithChildren
  AuthenticatedMeetingRoute: typeof AuthenticatedMeetingRoute
  AuthenticatedPatientRoute: typeof AuthenticatedPatientRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDoctorRoute: AuthenticatedDoctorRouteWithChildren,
  AuthenticatedMeetingRoute: AuthenticatedMeetingRoute,
  AuthenticatedPatientRoute: AuthenticatedPatientRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
